### ISSUE TITLE
BEBA switch with ONOS

### ISSUE THREAD

**Issue by ghost** [beba-eu/beba-switch#52]
Hello @DavideSanvito ,

I want to use the BEBA switch with ONOS controller and Mininet all running on the same Ubuntu machine. Does the swtich support ONOS and Mininet. And, is there a guide for the same.

Thanks
Pradeep Jha

**Comment by DavideSanvito** [comment]
Hi!
Yes, the switch is ready to be used with Mininet: the instruction reported in https://beba-eu.github.io/ let you install both the BEBA switch and controller in a Mininet VM.
I do not know if ONOS currently supports the original CPqD softswitch we forked, probably @ccascone knows the answer, but I'm sure it does not support the configuration of stateful processing provided by our  BEBA extension.
Best,
Davide

**Comment by ccascone** [comment]
Hi @pjpradeepjha,

ONOS supports any switch compatible with the OpenFlow specification, as such it also support beba-switch. However, beba-switch supports more capabilities than a standard OpenFlow switch. Indeed, it offer supports for stateful packet processing and packet generation. These features are not supported by the current version of ONOS, as they require support for some OpenFlow extension messages that are currently not understood by ONOS. In conclusion, if you want to use beba-switch as a standard OpenFlow 1.3 switch, then you can use it with ONOS, otherwise I suggest using the RYU-base beba controller (https://github.com/beba-eu/beba-ctrl/).

On how to run ONOS and beba-switch with Mininet you can use this tutorial:
https://wiki.onosproject.org/display/ONOS/Running+ONOS+with+onos.py

Make sure to install beba-switch in your VM using these instructions:
https://beba-eu.github.io/

When it comes to running mininet, make sure to use the following command to start ONOS along with beba-switch:
`sudo mn --custom onos.py --controller onos,3 --switch onosuser --topo torus,4,4`

Hope it helps.

Cheers.
Carmelo

**Comment by ghost** [comment]
@ccascone  @DavideSanvito  Thank you so much for your answers. I'll try out all the instructions you guys suggested. Thanks again. :)
