### ISSUE TITLE
Turns OpenWrt router into OpenFlow switches with beba-switch

### ISSUE THREAD

**Issue by valsonpereira** [beba-eu/beba-switch#55]
Hi everyone;

how can i turn a OpenWrt router into OpenFlow switches with beba-switch?

Thanks

**Comment by ccascone** [comment]
Hi @ValsonPereira, at a high level the steps you need to perform are: (1) build and install beba-switch on your OpenWRT platform, (2) execute beba-switch assigning the physical ports of your router (when starting the ofdatapath process). For (1), I'm not sure all the dependencies to build beba-switch are available for OpenWRT. Let us know if you succeed. Closing this since it's not a real issue.
